print("----------CONVERSACION DE CHISTE-----------")
print("Que lindos perritos los tuyos! Que raza son?")
print("Uno es Dalmata")
print("Y el otro?")
print("Tambien")
print("Y son machos?")
print("Uno si")
print("Y el otro?")
print("Tambien")
print("Poque me dices uno si y despues el otro tambien antes de decir los dos?")
print("Es que uno es mio...")
print("Ahh!! Y el otro?")
print("Tambien")
